version: '3.8'

services:
  postgres:
    container_name: IPL_DB
    build: ./docker/postgres
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

networks:
  backend:
    driver: bridge
